environment:

  # Python versions that will be tested
  # Note: it defines variables that can be used later
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.12"
      PYTHON_ARCH: "32"

# There is no build phase for Python
build: off

# Install WinPcap
install:
  # Installing WinPcap directly does not work,
  # see http://help.appveyor.com/discussions/problems/2280-winpcap-installation-issue
  - choco install -y nmap
  - refreshenv

# Launch tests
test_script:
  - 'dir "C:\Program Files (x86)"
  - 'dir "C:\"
  - echo %PYTHONPATH% %APPVEYOR_BUILD_FOLDER%
  - set PYTHONPATH=%APPVEYOR_BUILD_FOLDER%
  - 'cd "C:\\Program Files (x86)\Nmap"; nmap -h'
  - "%PYTHON%\\python test/dump_conf.py"
