environment:

  # Python versions that will be tested
  # Note: it defines variables that can be used later
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.12"
      PYTHON_ARCH: "32"

# There is no build phase for Python
build: off

# Launch tests
test_script:
  - echo %PYTHONPATH% %APPVEYOR_BUILD_FOLDER%
  - set PYTHONPATH=%APPVEYOR_BUILD_FOLDER%
  - echo %PYTHONPATH% %APPVEYOR_BUILD_FOLDER%
  - %PYTHON%\\python test/dump_conf.py
